/*
Italian eInvoice API

The Italian eInvoice API is a RESTful API that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed by Invoicetronic to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. The API also provides advanced features as encryption at rest, invoice validation, multiple upload formats, webhooks, event logging, client SDKs for commonly used languages, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/

API version: 1.0.0
Contact: support@invoicetronic.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicesdk

import (
	"encoding/json"
)

// checks if the DatiTrasmissione type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DatiTrasmissione{}

// DatiTrasmissione struct for DatiTrasmissione
type DatiTrasmissione struct {
	IdTrasmittente *IdTrasmittente `json:"id_trasmittente,omitempty"`
	ProgressivoInvio NullableString `json:"progressivo_invio,omitempty"`
	FormatoTrasmissione NullableString `json:"formato_trasmissione,omitempty"`
	CodiceDestinatario NullableString `json:"codice_destinatario,omitempty"`
	ContattiTrasmittente *ContattiTrasmittente `json:"contatti_trasmittente,omitempty"`
	PecDestinatario NullableString `json:"pec_destinatario,omitempty"`
}

// NewDatiTrasmissione instantiates a new DatiTrasmissione object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDatiTrasmissione() *DatiTrasmissione {
	this := DatiTrasmissione{}
	return &this
}

// NewDatiTrasmissioneWithDefaults instantiates a new DatiTrasmissione object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDatiTrasmissioneWithDefaults() *DatiTrasmissione {
	this := DatiTrasmissione{}
	return &this
}

// GetIdTrasmittente returns the IdTrasmittente field value if set, zero value otherwise.
func (o *DatiTrasmissione) GetIdTrasmittente() IdTrasmittente {
	if o == nil || IsNil(o.IdTrasmittente) {
		var ret IdTrasmittente
		return ret
	}
	return *o.IdTrasmittente
}

// GetIdTrasmittenteOk returns a tuple with the IdTrasmittente field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatiTrasmissione) GetIdTrasmittenteOk() (*IdTrasmittente, bool) {
	if o == nil || IsNil(o.IdTrasmittente) {
		return nil, false
	}
	return o.IdTrasmittente, true
}

// HasIdTrasmittente returns a boolean if a field has been set.
func (o *DatiTrasmissione) HasIdTrasmittente() bool {
	if o != nil && !IsNil(o.IdTrasmittente) {
		return true
	}

	return false
}

// SetIdTrasmittente gets a reference to the given IdTrasmittente and assigns it to the IdTrasmittente field.
func (o *DatiTrasmissione) SetIdTrasmittente(v IdTrasmittente) {
	o.IdTrasmittente = &v
}

// GetProgressivoInvio returns the ProgressivoInvio field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DatiTrasmissione) GetProgressivoInvio() string {
	if o == nil || IsNil(o.ProgressivoInvio.Get()) {
		var ret string
		return ret
	}
	return *o.ProgressivoInvio.Get()
}

// GetProgressivoInvioOk returns a tuple with the ProgressivoInvio field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DatiTrasmissione) GetProgressivoInvioOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProgressivoInvio.Get(), o.ProgressivoInvio.IsSet()
}

// HasProgressivoInvio returns a boolean if a field has been set.
func (o *DatiTrasmissione) HasProgressivoInvio() bool {
	if o != nil && o.ProgressivoInvio.IsSet() {
		return true
	}

	return false
}

// SetProgressivoInvio gets a reference to the given NullableString and assigns it to the ProgressivoInvio field.
func (o *DatiTrasmissione) SetProgressivoInvio(v string) {
	o.ProgressivoInvio.Set(&v)
}
// SetProgressivoInvioNil sets the value for ProgressivoInvio to be an explicit nil
func (o *DatiTrasmissione) SetProgressivoInvioNil() {
	o.ProgressivoInvio.Set(nil)
}

// UnsetProgressivoInvio ensures that no value is present for ProgressivoInvio, not even an explicit nil
func (o *DatiTrasmissione) UnsetProgressivoInvio() {
	o.ProgressivoInvio.Unset()
}

// GetFormatoTrasmissione returns the FormatoTrasmissione field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DatiTrasmissione) GetFormatoTrasmissione() string {
	if o == nil || IsNil(o.FormatoTrasmissione.Get()) {
		var ret string
		return ret
	}
	return *o.FormatoTrasmissione.Get()
}

// GetFormatoTrasmissioneOk returns a tuple with the FormatoTrasmissione field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DatiTrasmissione) GetFormatoTrasmissioneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FormatoTrasmissione.Get(), o.FormatoTrasmissione.IsSet()
}

// HasFormatoTrasmissione returns a boolean if a field has been set.
func (o *DatiTrasmissione) HasFormatoTrasmissione() bool {
	if o != nil && o.FormatoTrasmissione.IsSet() {
		return true
	}

	return false
}

// SetFormatoTrasmissione gets a reference to the given NullableString and assigns it to the FormatoTrasmissione field.
func (o *DatiTrasmissione) SetFormatoTrasmissione(v string) {
	o.FormatoTrasmissione.Set(&v)
}
// SetFormatoTrasmissioneNil sets the value for FormatoTrasmissione to be an explicit nil
func (o *DatiTrasmissione) SetFormatoTrasmissioneNil() {
	o.FormatoTrasmissione.Set(nil)
}

// UnsetFormatoTrasmissione ensures that no value is present for FormatoTrasmissione, not even an explicit nil
func (o *DatiTrasmissione) UnsetFormatoTrasmissione() {
	o.FormatoTrasmissione.Unset()
}

// GetCodiceDestinatario returns the CodiceDestinatario field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DatiTrasmissione) GetCodiceDestinatario() string {
	if o == nil || IsNil(o.CodiceDestinatario.Get()) {
		var ret string
		return ret
	}
	return *o.CodiceDestinatario.Get()
}

// GetCodiceDestinatarioOk returns a tuple with the CodiceDestinatario field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DatiTrasmissione) GetCodiceDestinatarioOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CodiceDestinatario.Get(), o.CodiceDestinatario.IsSet()
}

// HasCodiceDestinatario returns a boolean if a field has been set.
func (o *DatiTrasmissione) HasCodiceDestinatario() bool {
	if o != nil && o.CodiceDestinatario.IsSet() {
		return true
	}

	return false
}

// SetCodiceDestinatario gets a reference to the given NullableString and assigns it to the CodiceDestinatario field.
func (o *DatiTrasmissione) SetCodiceDestinatario(v string) {
	o.CodiceDestinatario.Set(&v)
}
// SetCodiceDestinatarioNil sets the value for CodiceDestinatario to be an explicit nil
func (o *DatiTrasmissione) SetCodiceDestinatarioNil() {
	o.CodiceDestinatario.Set(nil)
}

// UnsetCodiceDestinatario ensures that no value is present for CodiceDestinatario, not even an explicit nil
func (o *DatiTrasmissione) UnsetCodiceDestinatario() {
	o.CodiceDestinatario.Unset()
}

// GetContattiTrasmittente returns the ContattiTrasmittente field value if set, zero value otherwise.
func (o *DatiTrasmissione) GetContattiTrasmittente() ContattiTrasmittente {
	if o == nil || IsNil(o.ContattiTrasmittente) {
		var ret ContattiTrasmittente
		return ret
	}
	return *o.ContattiTrasmittente
}

// GetContattiTrasmittenteOk returns a tuple with the ContattiTrasmittente field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatiTrasmissione) GetContattiTrasmittenteOk() (*ContattiTrasmittente, bool) {
	if o == nil || IsNil(o.ContattiTrasmittente) {
		return nil, false
	}
	return o.ContattiTrasmittente, true
}

// HasContattiTrasmittente returns a boolean if a field has been set.
func (o *DatiTrasmissione) HasContattiTrasmittente() bool {
	if o != nil && !IsNil(o.ContattiTrasmittente) {
		return true
	}

	return false
}

// SetContattiTrasmittente gets a reference to the given ContattiTrasmittente and assigns it to the ContattiTrasmittente field.
func (o *DatiTrasmissione) SetContattiTrasmittente(v ContattiTrasmittente) {
	o.ContattiTrasmittente = &v
}

// GetPecDestinatario returns the PecDestinatario field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DatiTrasmissione) GetPecDestinatario() string {
	if o == nil || IsNil(o.PecDestinatario.Get()) {
		var ret string
		return ret
	}
	return *o.PecDestinatario.Get()
}

// GetPecDestinatarioOk returns a tuple with the PecDestinatario field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DatiTrasmissione) GetPecDestinatarioOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PecDestinatario.Get(), o.PecDestinatario.IsSet()
}

// HasPecDestinatario returns a boolean if a field has been set.
func (o *DatiTrasmissione) HasPecDestinatario() bool {
	if o != nil && o.PecDestinatario.IsSet() {
		return true
	}

	return false
}

// SetPecDestinatario gets a reference to the given NullableString and assigns it to the PecDestinatario field.
func (o *DatiTrasmissione) SetPecDestinatario(v string) {
	o.PecDestinatario.Set(&v)
}
// SetPecDestinatarioNil sets the value for PecDestinatario to be an explicit nil
func (o *DatiTrasmissione) SetPecDestinatarioNil() {
	o.PecDestinatario.Set(nil)
}

// UnsetPecDestinatario ensures that no value is present for PecDestinatario, not even an explicit nil
func (o *DatiTrasmissione) UnsetPecDestinatario() {
	o.PecDestinatario.Unset()
}

func (o DatiTrasmissione) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DatiTrasmissione) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IdTrasmittente) {
		toSerialize["id_trasmittente"] = o.IdTrasmittente
	}
	if o.ProgressivoInvio.IsSet() {
		toSerialize["progressivo_invio"] = o.ProgressivoInvio.Get()
	}
	if o.FormatoTrasmissione.IsSet() {
		toSerialize["formato_trasmissione"] = o.FormatoTrasmissione.Get()
	}
	if o.CodiceDestinatario.IsSet() {
		toSerialize["codice_destinatario"] = o.CodiceDestinatario.Get()
	}
	if !IsNil(o.ContattiTrasmittente) {
		toSerialize["contatti_trasmittente"] = o.ContattiTrasmittente
	}
	if o.PecDestinatario.IsSet() {
		toSerialize["pec_destinatario"] = o.PecDestinatario.Get()
	}
	return toSerialize, nil
}

type NullableDatiTrasmissione struct {
	value *DatiTrasmissione
	isSet bool
}

func (v NullableDatiTrasmissione) Get() *DatiTrasmissione {
	return v.value
}

func (v *NullableDatiTrasmissione) Set(val *DatiTrasmissione) {
	v.value = val
	v.isSet = true
}

func (v NullableDatiTrasmissione) IsSet() bool {
	return v.isSet
}

func (v *NullableDatiTrasmissione) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDatiTrasmissione(val *DatiTrasmissione) *NullableDatiTrasmissione {
	return &NullableDatiTrasmissione{value: val, isSet: true}
}

func (v NullableDatiTrasmissione) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDatiTrasmissione) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


